In [2]:
import pandas as pd

In [3]:
df= pd.read_csv(r"../data/raw/credit_card_fraud_dataset.csv")

In [4]:
df

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
0,1,03-04-2024,4189.27,688,refund,San Antonio,0
1,2,19-03-2024,2659.71,109,refund,Dallas,0
2,3,08-01-2024,784.00,394,purchase,New York,0
3,4,13-04-2024,3514.40,944,purchase,Philadelphia,0
4,5,12-07-2024,369.07,475,purchase,Phoenix,0
...,...,...,...,...,...,...,...
99995,99996,07-06-2024,1057.29,289,refund,San Antonio,0
99996,99997,22-10-2023,297.25,745,refund,San Antonio,0
99997,99998,31-05-2024,3448.56,690,purchase,San Antonio,0
99998,99999,18-10-2024,3750.79,644,purchase,Philadelphia,0
99999,100000,05-03-2024,1596.79,675,refund,Houston,0

In [8]:

df["TransactionDate"] = pd.to_datetime(
    df["TransactionDate"],
    format="%d-%m-%Y",
    errors="coerce"
)

df = df.drop_duplicates()

df = df.dropna(subset=["TransactionDate"])

df = df[df["Amount"] > 0]

df = df[df["IsFraud"].isin([0, 1])]

df.reset_index(drop=True, inplace=True)

print("Cleaned Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nFraud Distribution:")
print(df["IsFraud"].value_counts())

display(df.head())

Cleaned Dataset Shape: (100000, 7)

Missing Values:
TransactionID      0
TransactionDate    0
Amount             0
MerchantID         0
TransactionType    0
Location           0
IsFraud            0
dtype: int64

Duplicate Rows: 0

Fraud Distribution:
IsFraud
0    99000
1     1000
Name: count, dtype: int64

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
0,1,2024-04-03,4189.27,688,refund,San Antonio,0
1,2,2024-03-19,2659.71,109,refund,Dallas,0
2,3,2024-01-08,784.00,394,purchase,New York,0
3,4,2024-04-13,3514.40,944,purchase,Philadelphia,0
4,5,2024-07-12,369.07,475,purchase,Phoenix,0

In [9]:
df.to_csv(
    "../data/processed/credit_card_fraud_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [10]:
from pathlib import Path

file_path = Path("../data/processed/credit_card_fraud_cleaned.csv")

print("File exists:", file_path.exists())

File exists: True